### ISSUE TITLE
Can you build the image again and push to Docker Hub?

### ISSUE THREAD

**Issue by zerolfx** [NinetailLabs/syncplay-server#4]
The latest image from Docker Hub cannot run. But if I build it again from your code, it works normally.

```
Unable to find image 'ninetaillabs/syncplay-server:latest' locally
latest: Pulling from ninetaillabs/syncplay-server
05e7bc50f07f: Pull complete 
95a294b7a509: Pull complete 
2bd4182478f7: Pull complete 
190672ff1074: Pull complete 
1b4b65d68988: Pull complete 
56d985687a12: Pull complete 
c0ad0df875b8: Pull complete 
9950974055f4: Pull complete 
de95e242bf8b: Pull complete 
edd5f6994b33: Pull complete 
b6f264bd5d43: Pull complete 
Digest: sha256:a609b942cb8d4d7e10a19ca6ac24d55a497f0e6377b6c22bbd2419c7a2c8f452
Status: Downloaded newer image for ninetaillabs/syncplay-server:latest
Traceback (most recent call last):
  File "./syncplayServer.py", line 15, in <module>
    from syncplay import ep_server
  File "/app/syncplay/syncplay/ep_server.py", line 3, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 31, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python3.7/site-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 149, in <module>
    OP_NO_TLSv1_3 = _lib.SSL_OP_NO_TLSv1_3
AttributeError: module 'lib' has no attribute 'SSL_OP_NO_TLSv1_3'
```

**Comment by zerolfx** [comment]
By the way, why not install python dependencies from requirements.txt?

**Comment by DeadlyEmbrace** [comment]
Apologies for the delay, was out over the weekend.
I have rebuilt _latest_ so please try again.

> By the way, why not install python dependencies from requirements.txt?
To be honest I haven't really played with docker in a log time, so not 100% sure how to do this. Currently I just try and keep the server version up to date with the SyncPlay release. If I have some time I will look into this, otherwise you are welcome to make an update and submit a pull request.

**Comment by zerolfx** [comment]
Thank you~
The latest version works fine, and I will try to update and submit a PR later.
